package define

const(
	SUCCESS_CODE = 0
	SUCCESS_MSG = "请求成功"
	// System exception
	ERR_SYSTEM_EXCEPTION_CODE = -11
	ERR_SYSTEM_EXCEPTION_MSG = "系统异常"

	ERR_PARAM_VAILD_CODE = -1
	ERR_PARAM_VAILD_MSG = "参数验证出错"

	// mysql exception
	ERR_MYSQL_EXCEPTION_CODE = -12
	ERR_MYSQL_EXCEPTION_MSG = "数据库操作异常"

	// -1001 -1100  用户相关
	ERR_USER_EXIST_CODE = -1001
	ERR_USER_EXIST_MSG = "用户名已存在"
	ERR_USER_PASSWORD_CODE = -1002
	ERR_USER_PASSWORD_MSG = "用户名密码有误"



)